### ISSUE TITLE
Draft a new release

### ISSUE THREAD

**Issue by pratik-fractl** [fractl-io/fractl#1272]
New version will have breaking changes, as we have switched from `/_e/` to `/api/` endpoints. So, couple of changes need to be made.

- [x] Complete #1244 
- [x] #1279
- [x] #1280
- [x] Update Knowledgebase endpoints
- [ ] Update Fx client endpoints (if necessary)
- [ ] Update Copilot endpoints (if necessary)
- [x] Update Fractl Deployment service
- [x] Update bin/fractl
- [ ] Notify Fractl discord
- [x] Complete #1243

**Comment by vijayfractl** [comment]
version 0.5.1 released.
