### ISSUE TITLE
upsert user post cognito auth/user-login

### ISSUE THREAD

**Issue by pratik-fractl** [fractl-io/fractl#1323]
Following discussion in this [thread](https://fractlhq.slack.com/archives/C0426UM62PQ/p1715231513915939).

**Comment by vijayfractl** [comment]
@pratik-fractl fixed here: https://github.com/fractl-io/fractl/commit/4b607733ac1e0c20c324cb575bf1517ab9567e09

**Comment by pratik-fractl** [comment]
Thanks @vijayfractl!
