### ISSUE TITLE
Running `lein run` after `fractl publish local` and changed files

### ISSUE THREAD

**Issue by muazzam0x48** [fractl-io/fractl#1325]
For a sample project:

`abc/core.fractl`

```
(component :Abc.Core)

(entity
 :Order
 {:Id :UUID
  :Name :String
  :SubmitDate :Now})
```

`model.fractl`
```
{:name :Abc
 :fractl-version "current"
 :components [:Abc.Core]}
```

Running `fractl publish local` creates out directory and compiles it to Clojure code.

At this point, `lein run` works fine. But if I `touch src/abc/model/abc/core.cljc` (or modify in any way), it results in this error when I try to run lein again:

```
Syntax error macroexpanding at (core.cljc:17:1).
Execution error at jdk.internal.reflect.DirectConstructorHandleAccessor/newInstance (DirectConstructorHandleAccessor.java:62).
invalid attribute specification - [:SubmitDate nil]

Full report at:
/tmp/clojure-123780034211234090.edn
Compilation failed: Subprocess failed (exit code: 1)
```

But it's fixed if I touch model.cljc and other files afterwards.

**Comment by vijayfractl** [comment]
fixed here: https://github.com/fractl-io/fractl/commit/eb82e56f0fb729595eb81b7352f905accd5432b5
