### ISSUE TITLE
Release new Fractl version 0.5.2

### ISSUE THREAD

**Issue by pratik-fractl** [fractl-io/fractl#1358]
We are almost ready for a new Fractl release. Here are some release's checklist:

- [ ] Review and update docs to reflect the new language constructs.
- [x] Trigger release via CI
- [x] Update checksums on Fractl script.
- [ ] Release manually to Clojars.

**Comment by vijayfractl** [comment]
About documentation - There's not much information in the docs about `model.fractl`. Also there will be some more changes to the syntax of the new `resolver` construct. I think both these can be done after the 0.5.2 release.
